encoder_kwargs:
  rna:
    dims: [512, 300, 128]
    norm: true
    norm_type: batchnorm
    dropout: false
    dropout_p: 0.0
  atac:
    dims: [1024, 512, 128]
    norm: true
    norm_type: batchnorm
    dropout: false
    dropout_p: 0.0
learning_rate: 0.001
weight_decay: 0.0001
covariate_specific_theta: false
multimodal: true
is_binarized: true
encoder_multimodal_joint_layers: null

